apiVersion: v1
kind: Service
metadata:
  name: redis-database-service
spec:
  selector:
    app: redis-database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-database
  template:
    metadata:
      labels:
        app: redis-database
    spec:
      containers:
      - name: redis-database-container
        image: redis:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
        envFrom:
        - configMapRef:
            name: redis-config
---
