version: '3.8'
networks:
  tsvi_network:
    driver: bridge

services:
  database:
    networks:
      - tsvi_network
    container_name: postgres_database_container
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    networks:
      - tsvi_network
    container_name: redis_container
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"

  app:
    networks:
      - tsvi_network
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:8086"
    container_name: spring_app_container
    depends_on:
      - database
      - redis
    restart: on-failure
    environment: 
      - USER_NAME=postgres
      - DB_URL=jdbc:postgresql://database:5432/postgres
      - PASSWORD=postgres
      - CHANGELOG_VERSION=changelog_version-3.3.xml
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  postgresql-data: