apiVersion: v1
kind: Service
metadata:
  name: redis-database-service
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redisDatabaseService.type }}
  selector:
    app: redis-database
  {{- include "my-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.redisDatabaseService.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-chart.fullname" . }}-redis-config
  labels:
    app: redis
  {{- include "my-chart.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-redis-database-deployment
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redisDatabaseDeployment.replicas }}
  selector:
    matchLabels:
      app: redis-database
    {{- include "my-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis-database
      {{- include "my-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "my-chart.fullname" . }}-redis-config
        image: {{ .Values.redisDatabaseDeployment.redisDatabaseContainer.image.repository
          }}:{{ .Values.redisDatabaseDeployment.redisDatabaseContainer.image.tag | default
          .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.redisDatabaseDeployment.redisDatabaseContainer.imagePullPolicy
          }}
        name: redis-database-container
        ports:
        - containerPort: 6379
        resources: {{- toYaml .Values.redisDatabaseDeployment.redisDatabaseContainer.resources
          | nindent 10 }}

