apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-v2
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.v2.replicas }}
  selector:
    matchLabels:
      app: spring-app
    {{- include "my-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: spring-app
        version: v2
      {{- include "my-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_URL
          value: {{ .Values.v2.springAppContainer.env.dbUrl }}
        - name: USER_NAME
          value: {{ .Values.v2.springAppContainer.env.userName }}
        - name: PASSWORD
          value: {{ .Values.v2.springAppContainer.env.password }}
        - name: CHANGELOG_VERSION
          value: {{ .Values.v2.springAppContainer.env.changelogVersion }}
        - name: REDIS_HOST
          value: {{ .Values.v2.springAppContainer.env.redisHost }}
        - name: SEARCH_FEATURE_FLAG
          value: {{ .Values.v2.springAppContainer.env.searchFeatureFlag | quote }}
        image: {{ .Values.v2.springAppContainer.image.repository }}:{{ .Values.v2.springAppContainer.image.tag }}
        imagePullPolicy: Always
        name: spring-app-container
        ports:
        - containerPort: 8086
        resources:
          limits:
            cpu: {{ .Values.v2.springAppContainer.resources.limits.cpu }}
            memory: {{ .Values.v2.springAppContainer.resources.limits.memory }}
          requests:
            cpu: {{ .Values.v2.springAppContainer.resources.requests.cpu }}
            memory: {{ .Values.v2.springAppContainer.resources.requests.memory }}
      imagePullSecrets:
      - name: your-registry-secret