apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-v1
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.v1.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: spring-app
    {{- include "my-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: spring-app
        version: v1
      {{- include "my-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_URL
          value: {{ .Values.v1.springAppContainer.env.dbUrl }}
        - name: USER_NAME
          value: {{ .Values.v1.springAppContainer.env.userName }}
        - name: PASSWORD
          value: {{ .Values.v1.springAppContainer.env.password }}
        - name: CHANGELOG_VERSION
          value: {{ .Values.v1.springAppContainer.env.changelogVersion }}
        - name: REDIS_HOST
          value: {{ .Values.v1.springAppContainer.env.redisHost }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        - name: SEARCH_FEATURE_FLAG
          value: {{ .Values.v1.springAppContainer.env.searchFeatureEnabled | quote }}
        image: {{ .Values.v1.springAppContainer.image.repository }}:{{ .Values.v1.springAppContainer.image.tag }}
        imagePullPolicy: Always
        name: spring-app-container
        ports:
        - containerPort: 8086
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: {{ .Values.v1.springAppContainer.resources.limits.cpu }}
            memory: {{ .Values.v1.springAppContainer.resources.limits.memory }}
          requests:
            cpu: {{ .Values.v1.springAppContainer.resources.requests.cpu }}
            memory: {{ .Values.v1.springAppContainer.resources.requests.memory }}
      imagePullSecrets:
      - name: your-registry-secret